config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :beers
  resources :breweries
  #resources :ratings
  resources :ratings, only: [:index, :new, :create, :destroy]
  resource :session, only: [:new, :create, :destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "breweries#index"
  #get 'ratings', to: 'ratings#index'
  #get 'ratings/new', to: 'ratings#new'
  #post 'ratings', to: 'ratings#create'
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
end

app/models/brewery.rb
class Brewery < ApplicationRecord
  include RatingAverage

  has_many :beers, dependent: :destroy
  has_many :ratings, through: :beers

  validates :score, numericality: { greater_than_or_equal_to: 1040,
    less_than_or_equal_to: 2022,
    only_integer: true }
  validates :name, presence: true


  def to_s
    name
  end
end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController
  before_action :set_brewery, only: %i[show edit update destroy]
  before_action :authenticate, only: [:destroy]

  # GET /breweries or /breweries.json
  def index
    @breweries = Brewery.all
    # render :panimot
  end

  # GET /breweries/1 or /breweries/1.json
  def show
  end

  # GET /breweries/new
  def new
    @brewery = Brewery.new
  end

  # GET /breweries/1/edit
  def edit
  end

  # POST /breweries or /breweries.json
  def create
    @brewery = Brewery.new(brewery_params)

    respond_to do |format|
      if @brewery.save
        format.html { redirect_to brewery_url(@brewery), notice: "Brewery was successfully created." }
        format.json { render :show, status: :created, location: @brewery }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /breweries/1 or /breweries/1.json
  def update
    respond_to do |format|
      if @brewery.update(brewery_params)
        format.html { redirect_to brewery_url(@brewery), notice: "Brewery was successfully updated." }
        format.json { render :show, status: :ok, location: @brewery }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breweries/1 or /breweries/1.json
  def destroy
    @brewery.destroy

    respond_to do |format|
      format.html { redirect_to breweries_url, notice: "Brewery was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_brewery
    @brewery = Brewery.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def brewery_params
    params.require(:brewery).permit(:name, :year)
  end

  def authenticate
    admin_accounts = { "pekka" => "beer", "arto" => "foobar", "matti" => "ittam", "vilma" => "kangas" }

    authenticate_or_request_with_http_basic do |username, password|
      return true if admin_accounts > { username => password }

      raise "Wrong password or username"
    end
  end
end

app/helpers/breweries_helper.rb
module BreweriesHelper
end

app/views/breweries/_brewery.html.erb
<div id="<%= dom_id brewery %>">
  <h2>
    <strong>Name:</strong>
    <%= brewery.name %>
  </h2>

  <p>
    <i>Established in 
    <%= brewery.year %></i>
  </p>
  <p>
    <strong>Number of beers:</strong>
    <%= brewery.beers.count %>
  </p>
  <% brewery.beers.to_a %>
  <p>
    <% brewery.beers.each do |beer| %>
      <%= link_to beer.name, beer %>
    <% end %>
  </p>
  <p>
    <% if brewery.ratings.empty? %>
      Brewery has not yet been rated!
    <% else %>
      <p>Brewery has <%= pluralize(brewery.ratings.count, "rating") %> with an average of <%= brewery.average_rating %></p>
    <% end %>
  </p>
</div>

app/views/breweries/_form.html.erb
<%= form_with(model: brewery) do |form| %>
  <% if brewery.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(brewery.errors.count, "error") %> prohibited this brewery from being saved:</h2>

      <ul>
        <% brewery.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :year, style: "display: block" %>
    <%= form.number_field :year %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/breweries/edit.html.erb
<h1>Editing brewery</h1>

<%= render "form", brewery: @brewery %>

<br>

<div>
  <%= link_to "Show this brewery", @brewery %> |
  <%= link_to "Back to breweries", breweries_path %>
</div>

app/views/breweries/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Breweries</h1>

<p>Number of breweries: <%= @breweries.count %></p>

<div id="breweries">
  <% @breweries.each do |brewery| %>
    <div id="<%= dom_id brewery %>">
      <p>
        <strong>Name:</strong>
        <%= link_to brewery.name, brewery %>
      </p>
      <p>
        <strong>Year:</strong>
        <%= brewery.year %>
      </p>
    </div>
  <% end %>
</div>

<%= link_to "New brewery", new_brewery_path %>
<%= link_to "Beer list", beers_path %>
<%= link_to "Ratings list", ratings_path %>

app/views/breweries/new.html.erb
<h1>New brewery</h1>

<%= render "form", brewery: @brewery %>

<br>

<div>
  <%= link_to "Back to breweries", breweries_path %>
</div>

app/views/breweries/panimot.html.erb
<h2>Panimot</h2>

panimoita <%= @breweries.count %>

app/views/breweries/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @brewery %>

<div>
  <%= link_to "Edit this brewery", edit_brewery_path(@brewery) %> |
  <%= link_to "Back to breweries", breweries_path %>

  <%= button_to "Destroy this brewery", @brewery, method: :delete %>
</div>