config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :beers
  resources :breweries
  #resources :ratings
  resources :ratings, only: [:index, :new, :create, :destroy]
  resource :session, only: [:new, :create, :destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "breweries#index"
  #get 'ratings', to: 'ratings#index'
  #get 'ratings/new', to: 'ratings#new'
  #post 'ratings', to: 'ratings#create'
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ratebeer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="navibar">
      <%= link_to 'breweries', breweries_path %>
      <%= link_to 'beers', beers_path %>
      <%= link_to 'ratings', ratings_path %>
      <%= link_to 'users', users_path %> |
      <% if current_user %>
        <%= link_to current_user.username, current_user %> signed in, 
        <%= link_to 'Rate a new beer', new_rating_path %>,
        <%= link_to 'Signout', signout_path,
        data: { "turbo-method": :delete}, class: "link-secondary smooth" %>
      <% else %>
        <%= link_to 'Sign in', signin_url %>, <%= link_to 'Sign up', signup_url %>
      <% end %>
    </div>
    
    <%= yield %>
  </body>
</html>